### ISSUE TITLE
Create a release 1.0.0

### ISSUE THREAD

**Issue by pgrimaud** [winzou/tnt-express#1]
Hello @winzou 

Thank you so much for this little package.
Could you create one release? I'm not fan with dev-master dependencies in my composer.json file.

Thanks you so much 🙏

**Comment by winzou** [comment]
Hi @pgrimaud 
I've tagged a 1.0 release. I must admin this is working well in one of my project, but hasn't been extensively tested. If you find any issue, please do report it here.
Thanks!

**Comment by pgrimaud** [comment]
Perfect, thanks.

I will test this release on my side.
